config/routes.rb
Rails.application.routes.draw do
  get 'users/account'
  get 'users/profile'
  patch 'users/profile'
  post 'users/profile_edit', to: 'users#profile_update'
  get 'home/show'
  # get 'users/profile/edit', to: 'users#profile_edit'
  # post 'users/profile/edit', to: 'users#profile_edit'
  # patch 'users/profile/edit', to: 'users#profile_update'

  

  get 'rooms/own'
  
  
  get 'users/create'
  get 'users/new'
  get 'users/update'
  


  devise_scope :users do
    get 'users/edit', to: "users/registrations#edit"
  end

  resources :reservations do
    member do
      post 'confirm' => 'reservations#confirm'
      post 'back'
    end
  end

  root to: 'home#index'

  resources :rooms
  devise_for :users, controllers: { 
    sessions: 'users/sessions', 
    registrations: 'users/registrations'
  }
  
  get 'users/edit', to: 'users/registrations#edit'
  get 'users/profile_edit', to: 'users#profile_edit'
  
  post 'users/:id/edit' => 'users#profile'
  post 'reservations/:id' => 'reservations#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one_attached :avatar
  has_many :rooms, dependent: :destroy
  has_many :reservations, dependent: :destroy

  validates :username, presence: true, length: { maximum: 20 }
  validates :profile, length: { maximum: 200 }



end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end
 
  # GET /resource/edit
  def edit
    super
  end

  # # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  protected
  # アカウント編集後、プロフィール画面に移動する
  def after_update_path_for(resource)
    users_account_path(id: current_user.id)
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def account
        @user = User.find(current_user.id)
    end

    def profile
         @user = User.find(current_user.id)
    end

    def new  
        @user = User.new
    end

    def create 
        @user = User.create params.require(:user).permit(:username, :profile, :avatar, :email, :password)
        redirect_to "users_profile_path"
    end
    
    def profile_edit
        @user = User.find(current_user.id)
    end

    def profile_update
        binding.pry
        @user = User.find(current_user.id)
        if @user.update!(user_params)
            flash[:notice] = "プロフィールの情報を更新しました"
            redirect_to "users_profile_path"
          else
            flash.now[:alert] ="プロフィールの情報を更新できませんでした"
            render "users_profile_edit_path"
          end
    end


    private
    def user_params
        params.require(:user).permit(:username, :email, :profile, :avatar)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/account.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        アカウント
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <div class="columns is-centered">
        <div class="column is-3">
        <article class="panel is-link">
          <h2 class="panel-heading">
            設定
          </h2>
          <div class="panel-block">
            <p class="control">
              アカウント
            </p>
          </div>
            <%= link_to "プロフィール", users_profile_path, class: "panel-block"%>
        </article>
      </div>
          <div class="column is-8">
            <td>
              <%= link_to "編集", edit_user_registration_path, class: "button is-primary" %>
            </td>
            <table class="table is-fullwidth">
                <% if @user == current_user %>
                  <tr>
                    <td>メールアドレス</td>
                    <td class="is-size-4">
                    <%= @user.email %>
                    </td>
                  </tr>
                </div>
                  <tr>
                    <td>パスワード</td>
                    <td class="is-size-4">
                    ******
                    </td>
                  </tr>
                  
                <% end %>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/edit.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        プロフィール編集
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_with model: @user, url: users_profile_path, local: true do |f| %>
          <div class="field">
            <%= f.label :username, "ユーザー名", class: "label" %>
            <%= f.text_field :username, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :profile, "自己紹介", class: "label" %>
            <%= f.text_area :profile, class: "textarea" %>
          </div>

          <div class="field">
          <%= f.label :avatar, "アイコン画像", class: "label" %>
          <%= f.file_field :avatar, class: "input" %>
          </div>

          <%= f.submit "更新", class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/profile.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        プロフィール
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <div class="columns is-centered">
        <div class="column is-3">
        <article class="panel is-link">
          <h2 class="panel-heading">
            設定
          </h2>
          <div class="panel-block">
            <p class="control">
              プロフィール
            </p>
          </div>
            <%= link_to "アカウント", home_show_path, class: "panel-block"%>
        </article>
      </div>
          <div class="column is-4">
          <td>アイコン画像</td>
            <% if @user.avatar.attached? %>
              <figure class="image is-128x128"  style="margin-left: auto; margin-right: auto;">
              <%= image_tag @user.avatar, class: "avatar is-rounded" %>
              </figure>
            <% else %>
              <figure class="image is-128x128"  style="margin-left: auto; margin-right: auto;">
              <%= image_tag "no-image.png", class: "avatar is-rounded" %>
              </figure>
            <% end %>
          </div>
          <div class="column is-8">
            <table class="table is-fullwidth">
              <tr>
                <td>名前</td>
                <td class="is-size-4">
                  <strong><%= @user.username %></strong>
                </td>
              </tr>
              <tr>
                <td>自己紹介</td>
                <td>
                  <%= @user.profile %>
                </td>
              </tr>
              
                <% if @user == current_user %>
                    <%= link_to "編集", users_profile_edit_path(@user), class: "button is-primary" %>
                <% end %>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/profile_edit.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        プロフィール編集
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_with model: @user, url: users_profile_path, local: true do |f| %>
          <div class="field">
            <%= f.label :username, "ユーザー名", class: "label" %>
            <%= f.text_field :username, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :profile, "自己紹介", class: "label" %>
            <%= f.text_area :profile, class: "textarea" %>
          </div>

          <div class="field">
          <%= f.label :avatar, "アイコン画像", class: "label" %>
          <%= f.file_field :avatar, class: "input" %>
          </div>

          <%= f.submit "更新", class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        プロフィール
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <div class="columns is-centered">
        <div class="column is-3">
        <article class="panel is-link">
          <h2 class="panel-heading">
            設定
          </h2>
          <div class="panel-block">
            <p class="control">
              プロフィール
            </p>
          </div>
            <%= link_to "アカウント", "/users/account", class: "panel-block"%>
        </article>
      </div>
          <div class="column is-4">
          <td>アイコン画像</td>
            <% if @user.avatar.attached? %>
              <figure class="image is-128x128"  style="margin-left: auto; margin-right: auto;">
              <%= image_tag @user.avatar, class: "avatar is-rounded" %>
              </figure>
            <% else %>
              <figure class="image is-128x128"  style="margin-left: auto; margin-right: auto;">
              <%= image_tag "no-image.png", class: "avatar is-rounded" %>
              </figure>
            <% end %>
          </div>
          <div class="column is-8">
            <table class="table is-fullwidth">
              <tr>
                <td>名前</td>
                <td class="is-size-4">
                  <strong><%= @user.username %></strong>
                </td>
              </tr>
              <tr>
                <td>自己紹介</td>
                <td>
                  <%= @user.profile %>
                </td>
              </tr>
              
                <% if @user == current_user %>
                  <tr>
                    <td>メールアドレス</td>
                    <td class="is-size-4">
                    <%= @user.email %>
                    </td>
                  </tr>
                  <tr>
                    <td>パスワード</td>
                    <td class="is-size-4">
                    ******
                    </td>
                  </tr>
                  <td>
                    <%= link_to "編集", edit_user_path(@user), class: "button is-primary" %>
                  </td>
                <% end %>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
      