config/routes.rb
Rails.application.routes.draw do
  get 'users/account'
  get 'users/profile'
  patch 'users/profile'
  post 'users/profile_edit', to: 'users#profile_update'
  get 'home/show'
  # get 'users/profile/edit', to: 'users#profile_edit'
  # post 'users/profile/edit', to: 'users#profile_edit'
  # patch 'users/profile/edit', to: 'users#profile_update'

  

  get 'rooms/own'
  
  
  get 'users/create'
  get 'users/new'
  get 'users/update'
  


  devise_scope :users do
    get 'users/edit', to: "users/registrations#edit"
  end

  resources :reservations do
    member do
      post 'confirm' => 'reservations#confirm'
      post 'back'
    end
  end

  root to: 'home#index'

  resources :rooms
  devise_for :users, controllers: { 
    sessions: 'users/sessions', 
    registrations: 'users/registrations'
  }
  
  get 'users/edit', to: 'users/registrations#edit'
  get 'users/profile_edit', to: 'users#profile_edit'
  
  post 'users/:id/edit' => 'users#profile'
  post 'reservations/:id' => 'reservations#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def show
    @user = current_user
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="FirstView">
  <section class="container">
    <h2 class="FirstView_title">
      Potepan Shareで<br>
      まだ体験したことのない<br>
      旅をしよう
    </h2>
  </section>
</div>

app/views/home/show.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        アカウント
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <div class="columns is-centered">
        <div class="column is-3">
        <article class="panel is-link">
          <h2 class="panel-heading">
            設定
          </h2>
          <div class="panel-block">
            <p class="control">
              アカウント
            </p>
          </div>
            <%= link_to "プロフィール", users_profile_path, class: "panel-block"%>
        </article>
      </div>
          <div class="column is-8">
            <td>
              <%= link_to "編集", edit_user_registration_path, class: "button is-primary" %>
            </td>
            <table class="table is-fullwidth">
                <% if @user == current_user %>
                  <tr>
                    <td>メールアドレス</td>
                    <td class="is-size-4">
                    <%= @user.email %>
                    </td>
                  </tr>
                </div>
                  <tr>
                    <td>パスワード</td>
                    <td class="is-size-4">
                    ******
                    </td>
                  </tr>
                  
                <% end %>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>