config/routes.rb
Rails.application.routes.draw do
  get 'users/account'
  get 'users/profile'
  patch 'users/profile'
  post 'users/profile_edit', to: 'users#profile_update'
  get 'home/show'
  # get 'users/profile/edit', to: 'users#profile_edit'
  # post 'users/profile/edit', to: 'users#profile_edit'
  # patch 'users/profile/edit', to: 'users#profile_update'

  

  get 'rooms/own'
  
  
  get 'users/create'
  get 'users/new'
  get 'users/update'
  


  devise_scope :users do
    get 'users/edit', to: "users/registrations#edit"
  end

  resources :reservations do
    member do
      post 'confirm' => 'reservations#confirm'
      post 'back'
    end
  end

  root to: 'home#index'

  resources :rooms
  devise_for :users, controllers: { 
    sessions: 'users/sessions', 
    registrations: 'users/registrations'
  }
  
  get 'users/edit', to: 'users/registrations#edit'
  get 'users/profile_edit', to: 'users#profile_edit'
  
  post 'users/:id/edit' => 'users#profile'
  post 'reservations/:id' => 'reservations#index'
end

app/models/room.rb
class Room < ApplicationRecord
    belongs_to :user
    has_one_attached :image
    has_many :reservations

    validates :name , presence: true
    validates :address , presence: true
    validates :single_rate , presence: true , numericality: { greater_than_or_equal_to: 0 }

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @user = current_user
    @rooms = current_user.rooms #ログインユーザーの登録施設のみ表示
  end

  def new
    @room = current_user.rooms.build
  end

  def create
    @user = current_user
    @room = Room.new(room_params)
    @room.user_id = current_user.id
    if @room.save
      flash[:notice] = "宿泊施設を登録しました"
      redirect_to @room
    else 
      render :new
    end
  end

  def show
    @user = current_user
    @room = Room.find(params[:id])
    @reservation = Reservation.new
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])

    if @room.update(room_params)
      flash[:notice] = "宿泊施設を更新しました"
      redirect_to @room
    else
      render :edit
    end
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    flash[:notice] = "宿泊施設を削除しました"
    redirect_to :rooms
  end
  
  private
  def room_params
    params.require(:room).permit(:name, :introduce, :single_rate, :address, :image, :room_id).merge(user_id: current_user.id)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        施設情報の編集
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @room do |f| %>
          <div class="field">
            <%= f.label :name, "施設名", class: "label" %>
            <%= f.text_field :name, :placeholder => "ルーム名を入力", class: "input" %>
          </div>

          <div class="field">
            <%= f.label :introduce, "施設詳細", class: "label" %>
            <%= f.text_area :introduce, :placeholder => "施設の詳細を入力", class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :single_rate, "料金", class: "label" %>
            <%= f.text_field :single_rate, :placeholder => "一日あたりの料金を入力", class: "input" %>
          </div>

          <div class="field">
            <%= f.label :address, "住所", class: "label" %>
            <%= f.text_field :address, :placeholder => "住所を入力", class: "input" %>
          </div>

          <div class="field">
            <%= f.label :image_name, "施設画像", class: "label" %>
            <%= f.file_field :image_name, class: "input" %>
          </div>

          <%= f.submit '保存', class: "button is-success" %>
          <%= link_to "キャンセル",:back, class: "button" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/rooms/index.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
       登録済み施設一覧
      </h1>
    </div>
  </div>
</section>

<section class="section">
<table>
<thead>
  <tr>
    <th>画像</th>
    <th>施設名</th>
    <th>施設紹介</th>
    <th>料金</th>
    <th>作成日</th>
    <th>編集</th>
    <th>削除</th>
  </tr>
</thead>
<tbody>
  <% @rooms.each do |room| %>
    <tr>
      <td>
        <div>
        <% if room.image.attached? %>
        <% binding pry %>
          <%= image_tag  @room.image.url %>
        <% else %>
          <%= image_tag 'default-room.png' %>
        <% end %>
        </div>
      </td>                    
      <td><%= link_to room.name, room_path(room) %></td>
      <td><%= room.introduce %></td>
      <td>¥<%= room.single_rate %>〜</td>
      <td><%= room.updated_at&.strftime("%Y/%m/%d") %></td>
      <td><%= link_to "詳細" , room_path(room) %></td>
      <td><%= link_to "編集" , edit_room_path(room) %></td>
      <td><%= button_to "削除" , room_path(room), method: :delete , data: { confirm: "本当に削除しますか？" }%></td>
    </tr>
  <% end %>
</tbody>
</table>

<div class= "newroom">
  <%= link_to "新しい部屋の登録" , new_room_path, class: "button is-success" %>
</div>
</section>

app/views/rooms/new.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        新規登録
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @room do |f| %>
          <div class="field">
            <%= f.label :name, "施設名", class: "label" %>
            <%= f.text_field :name, :placeholder => "ルーム名を入力", class: "input" %>
          </div>

          <div class="field">
            <%= f.label :introduce, "施設詳細", class: "label" %>
            <%= f.text_area :introduce, :placeholder => "施設詳細を入力", class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :single_rate, "料金", class: "label" %>
            <%= f.text_field :single_rate, :placeholder => "一日あたりの料金を入力", class: "input" %>
          </div>

          <div class="field">
            <%= f.label :address, "住所", class: "label" %>
            <%= f.text_field :address, :placeholder => "住所を入力", class: "input" %>
          </div>

          <div class="field">
            <%= f.label :image_name, "施設画像", class: "label" %>
            <%= f.file_field :image_name, class: "input" %>
          </div>

          <%= f.submit '保存', class: "button is-success" %>
          <%= link_to "キャンセル",:back, class: "button" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/rooms/own.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
       登録済み一覧
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @rooms.each do |room| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
        
              <% if room.image.attached? %>
              <figure class="image is-4by3">
                <%= image_tag room.image %>
              </figure>
              <% else %> 
              <figure class="image is-4by3">
                <%= image_tag "default-room.png" %>
                </figure>
              <% end %>
              
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-left">
                  <%= room.introduce %>
                </div>
                <div class="media-content">
                  <%= room.created_at.to_s(:datetime_jp) %>
                </div>
              </div>
              <div class="content">
                <price>¥<%= room.single_rate %>〜</price>
              </div>
              <%= link_to "編集", edit_room_path(room.id), class: "button is-success" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/rooms/search.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        宿泊施設一覧
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @rooms.each do |room| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
            <%= image_tag room.image %>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-left">
                  <%= room.address %>
                </div>
                <div class="media-content">
                  <%= room.introduce %>
                </div>
              </div>
              <div class="content">
                <price>¥<%= room.single_rate %>〜</price>
              </div>
              <%= link_to "詳細はこちら", room_path(room), class: "button is-success" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/rooms/show.html.erb
<section class="section">
  <div class="container">
  <%= link_to "← 戻る",:back %>
    <div class="columns is-centered">
      <div class="column is-7">
        <div class="card">
          <div class="card-image">
          
            <% if @room.image.attached? %>
              <figure class="image is-4by3">
                <%= image_tag @room.imag.url %>
              </figure>
              <% else %>
              <figure class="image is-4by3">
                <%= image_tag "default-room.png" %>
              </figure>
            <% end %>

          </div>
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <p class="title is-4"><%= @room.name %></p>
              </div>
            </div>
            <div class="content">
              <table class="table is-narrow">
                <tr>
                  <td><%= simple_format @room.address %></td>
                </tr>
                <tr>
                  <td>¥<%= @room.single_rate %>〜</td>
                </tr>
                <tr>
                  <td><%= simple_format @room.introduce %></td>
                </tr>
              </table>
              <% if @room.user.id == current_user.id %>
                <%= link_to "編集", edit_room_path(@room), class: "button is-success" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      
    </div>
  </div>
</section>