config/routes.rb
Rails.application.routes.draw do
  get 'users/account'
  get 'users/profile'
  patch 'users/profile'
  post 'users/profile_edit', to: 'users#profile_update'
  get 'home/show'
  # get 'users/profile/edit', to: 'users#profile_edit'
  # post 'users/profile/edit', to: 'users#profile_edit'
  # patch 'users/profile/edit', to: 'users#profile_update'

  

  get 'rooms/own'
  
  
  get 'users/create'
  get 'users/new'
  get 'users/update'
  


  devise_scope :users do
    get 'users/edit', to: "users/registrations#edit"
  end

  resources :reservations do
    member do
      post 'confirm' => 'reservations#confirm'
      post 'back'
    end
  end

  root to: 'home#index'

  resources :rooms
  devise_for :users, controllers: { 
    sessions: 'users/sessions', 
    registrations: 'users/registrations'
  }
  
  get 'users/edit', to: 'users/registrations#edit'
  get 'users/profile_edit', to: 'users#profile_edit'
  
  post 'users/:id/edit' => 'users#profile'
  post 'reservations/:id' => 'reservations#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PoteshareApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
    <% end %>

    <nav class="navbar is-warning">
    <div class="navbar-brand">
      <%= link_to root_path, class: "navbar-item" do %>
        <h1 class="title is-4" style="font-family: cursive;">Potepan Share</h1>
      <% end %>
      <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>


    <% if user_signed_in? %>
      <div id="navbarExampleTransparentExample" class="navbar-menu">
        <div class="navbar-end">
          <% if current_user.avatar.attached? %>
            <p><%= image_tag current_user.avatar, class: "icon", style: "border-radius: 50%; width: 70px; height: 70px; object-fit:cover;" %></p>
          <% else %>
            <p><%= image_tag 'no-image.png',class: "icon", style: "border-radius: 50%; width: 70px; height: 70px; object-fit:cover;" %></p>
          <% end %>

          <div class="dropdown">
            <div class="dropdown-trigger">
              <button class="button" aria-haspopup="true" aria-controls="dropdown-menu">
                <span><%= current_user.username %></span>
                <span class="icon is-small">
                  <i class="fas fa-angle-down" aria-hidden="true"></i>
                </span>
              </button>
            </div>
            <div class="dropdown-menu" id="dropdown-menu" role="menu">
              <div class="dropdown-content">
                <a href="#" class="dropdown-item">
                  <%= link_to "施設の新規登録", new_room_path %>
                </a>
                <hr class="dropdown-divider">
                <a href="#" class="dropdown-item"> 
                  <%= link_to "予約済み一覧", reservations_path %>
                </a>
                <a href="#" class="dropdown-item"> 
                  <%= link_to "登録済み一覧", rooms_path %>
                </a>
                <a href="#" class="dropdown-item"> 
                  <%= link_to "アカウント設定", users_account_path %>
                </a>
                <hr class="dropdown-divider">
                <a href="#" class="dropdown-item"> 
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                </a>
              </div>
            </div>
          </div>
          <script>
               //DOMContentLoaded - it fires when initial HTML document has been completely loaded
               document.addEventListener('DOMContentLoaded', function () {
                  // querySelector - it returns the element within the document that matches the specified selector
                  var dropdown = document.querySelector('.dropdown');
                    
                  //addEventListener - attaches an event handler to the specified element.
                  dropdown.addEventListener('click', function(event) {
                    
                     //event.stopPropagation() - it stops the bubbling of an event to parent elements, by preventing parent event handlers from being executed
                     event.stopPropagation();
                      
                     //classList.toggle - it toggles between adding and removing a class name from an element
                     dropdown.classList.toggle('is-active');
                  });
               });        
            </script>
        </div>
    <% else %>
      <div id="navbarExampleTransparentExample" class="navbar-menu">
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">
              <p class="control">
                <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-light" %>
              </p>
              <p class="control">
                <%= link_to "新規登録", new_user_registration_path, class: "button is-warning is-light" %>
              </p>
            </div>
          </div>
        </div>
      </div>
    <% end %>

  </nav>

    <%= yield %>
  </body>
</html>